name: dart_kassakuitti_cli
description: A simple Dart CLI app to handle a cash receipt coming from S-kaupat or K-ruoka (two Finnish food online stores).
version: 0.15.0
homepage: https://github.com/areee/dart_kassakuitti_cli

environment:
  sdk: '>=2.17.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  lints: ^2.0.0
dependencies: 
  ansicolor: ^2.0.1
  args: ^2.3.1
  hive: ^2.2.2
  html: ^0.15.0
  intl: ^0.17.0
  path: ^1.8.2
  yaml: ^3.1.1

assets:
  - assets/files/