name: dart_kassakuitti_cli
description: A simple Dart CLI app to handle a cash receipt coming from S-kaupat or K-ruoka (two Finnish food online stores).
version: 2.5.0
homepage: https://github.com/areee/dart_kassakuitti_cli

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.2
  hive: ^2.2.3
  intl: ^0.18.0
  kassakuitti: ^0.3.0
  mime: ^1.0.4
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  lints: ^2.0.1
  test: ^1.22.2
