name: dart_kassakuitti_cli
description: A simple Dart CLI app to handle a cash receipt coming from S-kaupat or K-ruoka (two Finnish food online stores).
version: 2.14.0
homepage: https://github.com/areee/dart_kassakuitti_cli

environment:
  sdk: ^3.1.5

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  hive: ^2.2.3
  intl: ^0.18.1
  kassakuitti: ^0.9.0
  mime: ^1.0.4
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.9
